# Generated by Django 5.2.5 on 2025-08-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title_content', models.CharField(max_length=1000)),
                ('gallery_body_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_body_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_title_content', models.CharField(max_length=1000)),
                ('roadmap_body_content', models.TextField()),
                ('first_box_content', models.CharField(max_length=1000)),
                ('second_box_content', models.CharField(max_length=1000)),
                ('third_box_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title_content', models.CharField(max_length=1000)),
                ('section_body_content', models.TextField()),
            ],
        ),
    ]
