# Generated by Django 5.2.5 on 2025-08-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='first_box_content',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='second_box_content',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='third_box_content',
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_title_content', models.CharField(max_length=1000)),
                ('box_body_content', models.TextField()),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_boxes', to='page.roadmap')),
            ],
        ),
    ]
