# Generated by Django 5.2.5 on 2025-08-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'box', 'verbose_name_plural': 'boxes'},
        ),
    ]
