# Generated by Django 5.2.5 on 2025-08-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_box_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='box_body_content',
            new_name='box_body_giveaway',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='box_title_content',
            new_name='box_title_giveaway',
        ),
    ]
