# Generated by Django 5.2.5 on 2025-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_box_body_content_box_box_body_giveaway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WRP_title_content', models.CharField(max_length=1000)),
                ('WRP_body_content', models.TextField()),
            ],
        ),
    ]
