# Generated by Django 5.2.5 on 2025-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_wrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldParrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_parrot_title_content', models.CharField(max_length=1000)),
                ('world_parrot_body_content', models.TextField()),
            ],
        ),
    ]
